server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:

  mongodb:
    uri: mongodb://client_user:client_password@localhost:27017/client_db?authSource=client_db
    auto-index-creation: true

  data:
    mongodb:
      uri: mongodb://client_user:client_password@localhost:27017/client_db?authSource=client_db
app:
  version: "1.0"