server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery-service

eureka:
  instance:
    # Usa direto a variável enviada pelo Docker, caindo em discovery-service
    hostname: ${EUREKA_HOSTNAME:discovery-service}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # Deixamos a rota explícita e direta para não ter erro de parse
      defaultZone: http://discovery-service:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false # Evita travar registros no Docker