server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  profiles:
    active: native
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/product_db?authSource=admin
      auto-index-creation: true

app:
  version: 1.0