server:
  port: ${PORT:8083}
  wait-time-in-ms-when-sync-empty: 3000

spring:
  application:
    name: sale-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: sale_db
      username: sale_user
      password: sale_password
      authentication-database: sale_db
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  version: 1.0
