server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000


spring:

  mongodb:
    uri: mongodb://sale_user:sale_password@localhost:27017/sale_db?authSource=sale_db
    auto-index-creation: true

  data:
    mongodb:
      uri: mongodb://sale_user:sale_password@localhost:27017/sale_db?authSource=sale_db
app:
  version: 1.0
  productService:
    url: http://localhost:8082
    endpointConsultProduct: ${app.productService.url}/product
  clientService:
    url: http://localhost:8081
    endpointConsultClient: ${app.clientService.url}/client/exists/{id}

