spring.application.name=sale-service
spring.profiles.active=native
spring.mongodb.host=${MONGODB_HOST:localhost}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://root:root@localhost:8888}
app.version=1.0